//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGP_PRROJECT1.Theme.unify {
    
    
    public partial class _2page_project_record {
        
        /// <summary>
        /// Form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
        protected global::System.Web.UI.WebControls.GridView GridView1;

        protected global::System.Web.UI.WebControls.TextBox TextBox1;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected global::System.Web.UI.WebControls.TextBox TextBox2;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;


        protected global::System.Web.UI.WebControls.DropDownList DropDownList1;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;


        protected global::System.Web.UI.WebControls.TextBox TextBox3;

       // protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;

        protected global::System.Web.UI.WebControls.TextBox TextBox4;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
        protected global::System.Web.UI.WebControls.Button Button1;
        protected global::System.Web.UI.WebControls.Label Label1;
        protected global::System.Web.UI.WebControls.DropDownList DropDownList2;

    }
}
