//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGP_PRROJECT1.Theme.unify {
    
    
    public partial class _4page_create_task {
        protected global::System.Web.UI.WebControls.GridView GridView1;
   
        
    }
}
