//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGP_PRROJECT1.Theme.unify {
    
    
    public partial class _4page_progress {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.DropDownList DropDownList1;


        protected global::System.Web.UI.WebControls.Button Button1;

        protected global::System.Web.UI.WebControls.DropDownList DropDownList2;


        protected global::System.Web.UI.WebControls.Button Button2;



        protected global::System.Web.UI.WebControls.Panel Panel1;
        protected global::System.Web.UI.WebControls.Panel Panel2;
        protected global::System.Web.UI.WebControls.Panel Panel3;

        protected global::System.Web.UI.WebControls.GridView GridView1;

    }
}
