//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGP_PRROJECT1.Theme.unify
{


    public partial class _4page_create_task1
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.DropDownList DropDownList1;

      //  protected global::System.Web.UI.WebControls.Panel Panel1;
        protected global::System.Web.UI.WebControls.Panel Panel1;
        protected global::System.Web.UI.WebControls.Panel Panel2;
        protected global::System.Web.UI.WebControls.Panel Panel3;
        protected global::System.Web.UI.WebControls.DropDownList DropDownList2;
        protected global::System.Web.UI.WebControls.DropDownList DropDownList3;
       

        protected global::System.Web.UI.WebControls.TextBox  TextBox1;
        protected global::System.Web.UI.WebControls.TextBox TextBox2;
        protected global::System.Web.UI.WebControls.TextBox TextBox3;
        protected global::System.Web.UI.WebControls.TextBox TextBox4;
        protected global::System.Web.UI.WebControls.Label Label1;

        protected global::System.Web.UI.WebControls.Button Button1;
        protected global::System.Web.UI.WebControls.Button Button2;
        protected global::System.Web.UI.WebControls.Button Button3;


        protected global::System.Web.UI.WebControls.DropDownList DropDownList4;


        protected global::System.Web.UI.WebControls.DropDownList DropDownList5;
        protected global::System.Web.UI.WebControls.TextBox TextBox5;
        protected global::System.Web.UI.WebControls.TextBox TextBox6;
        protected global::System.Web.UI.WebControls.Button Button5;
       protected global::System.Web.UI.WebControls.FileUpload FileUpload1;
    
    }
}
